#!/usr/bin/env Rscript
library(ggplot2)
setwd('~/civic_nights')
load("./sinac2010_clean.Rda")
df<-transform(df,imss_rmm=100000*imss_nsbvv/(imss_nsbvv+imss_sbvv+imss_u))
df<-transform(df,ssa_rmm=100000*ssa_nsbvv/(ssa_nsbvv+ssa_sbvv+ssa_u))
df<-transform(df,smp_rmm=100000*smp_nsbvv/(smp_nsbvv+smp_sbvv+smp_u))
#p1 <- df(x=entidad,y=imss_rmm)
#p2 <- df(x=entidad,y=ssa_rmm)
#p2 <- df(x=entidad,y=smp_rmm)
#zz <- melt(list(p1=p1,p2=p2,p3=p3))

p <- ggplot(df, aes(x = entidad, y = imss_rmm)) + geom_point(colour = "green",size=12,label="IMSS")
p <- p + geom_text(data=df, mapping=aes(x=entidad, y=imss_rmm), label="SS", size=6)
p <- p + geom_point(aes(x = df$entidad, y = df$ssa_rmm),colour = "red",size=11,label="SSA")
p <- p + geom_text(mapping=aes(x=df$entidad, y=df$ssa_rmm), label="SP", size=6)
p <- p + geom_point(aes(x = df$entidad, y = df$smp_rmm),colour = "blue",size=10,label="Sector Privado")
p <- p + geom_text( mapping=aes(x=df$entidad, y=df$smp_rmm), label="Priv", size=6)
p <- p + ylab("Tasa de Mortalidad materna por cada 100000 nacimientos")
p <- p + xlab("Entidad")
p<-p+ggtitle('Mortalidad Materna, por Entidad, por Institución, 2010')
p <- p + theme(plot.title = element_text(size=20, face="bold", vjust=2))
#p <- p + theme(legend.title = element_text(colour="blue", size=16, face="bold"))
#p <- p + p +geom_point(aes(colour = factor(entidad),shape = factor(entidad)),size=6)
p
ggsave("inst.png",width = 10, height = 7, dpi = 120)